import { Typography } from "@material-ui/core";
import type { NextPage } from "next";
import Head from "next/head";
import TodoList from "../components/TodoList";
import MainLayout from "../layouts/MainLayout";

const HomePage: NextPage = () => {
  return (
    <MainLayout>
      <Head>
        <title>React Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Typography>Select a category to see todo items.</Typography>
    </MainLayout>
  );
};

export default HomePage;
